# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: API Gateway CI/CD

on:
  push:
    branches: [ "main" ]
env:
  GATEWAY_SCRIPT: ${{ vars.GATEWAY_HOME }}/shell/apigateway.sh
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |  
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean bootJar
    - name: Copy jar to EC2
      uses: appleboy/scp-action@master
      with:
        username: ${{ vars.USER }}
        host: api.134.works
        key: ${{ secrets.PRIVATE_KEY }}
        source: "./build/libs/*.jar"
        target: ${{ vars.GATEWAY_HOME }}
        strip_components: 2
    - name: Copy script to EC2
      uses: appleboy/scp-action@master
      with:
        username: ${{ vars.USER }}
        host: api.134.works
        key: ${{ secrets.PRIVATE_KEY }}
        source: "shell/apigateway.sh"
        target: ${{ vars.GATEWAY_HOME }}
    - name: Execute Script
      uses: appleboy/ssh-action@master
      with:
        username: ${{ vars.USER }}
        host: api.134.works
        key: ${{ secrets.PRIVATE_KEY }}
        script_stop: true
        script: chmod 744 ${{ env.GATEWAY_SCRIPT }} && ${{ env.GATEWAY_SCRIPT }}
